title: Thálassa
permalink: pretty
remote_theme: pmarsceill/just-the-docs
url: https://thalassa.zeruhur.space
logo: "/img/logo.png"
color_scheme: light
aux_links:
  "Thálassa on GitHub":
    - "//github.com/zeruhur/thalassa"
  "PDF":
    - "//zeruhur.itch.io/thalassa"
  "Lulu":
    - "//www.lulu.com/en/en/shop/roberto-bisceglie/th%C3%A1lassa/paperback/product-8gzn8n.html"
#  "Amazon":  
#    "//www.amazon.it/dp/B09HFXXJMC"
plugins:
  - jekyll-redirect-from
include:
    -js
exclude: [_build, booklet]

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "The text on this page is licensed under <a href=\"https://creativecommons.org/licenses/by-sa/4.0\">CC-BY-SA 4.0.</a>"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html