---
title: Thalassa
subtitle: Mythical Age Adventure Game
author: CC BY-SA 4.0 Roberto Bisceglie
nav_exclude: true
papersize: letter
fontfamily: Alegreya
documentclass: extbook
fontsize: 11 pt
toc: true
toc-depth: 1
header-includes: |
    \usepackage[paperheight=8.5in,paperwidth=5.5in, margin=0.5in]{geometry}
    \usepackage[utf8]{inputenc}
    \DeclareUnicodeCharacter{03A9}{\ensuremath{\Omega}}
---
\clearpage

\markboth{}{}